kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: testing
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
      hostname: web-server

